spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/ssafycommon
    username: ssafy
    password: ssafy
    driver-class-name: org.mariadb.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        
        
logging.level:
  org.hibernate.SQL: debug